### PR TITLE
Cider ritz

### PR DESCRIPTION
**Pull request by jjl**
Per issue #112, nrepl-mode is now cider-mode. The renaming stopped nrepl-ritz from working. This fixes it.

### CODE REVIEW

**Comment by jjl** [comment]
This is the minimal change to restore functionality. It might be advisable to rename things to have the cider- prefix in time.

**Comment by jjl** [comment]
Hrm, in trying to track down all of the other stuff that's been renamed, I found the following:

```
custard-tart% ag nrepl-dbg-detailed-frame-line-face
nrepl/elisp/cider-ritz.el
1280:        (nrepl-dbg-insert-frame frame 'nrepl-dbg-detailed-frame-line-face)
custard-tart% ag nrepl-dbg-frame-line-face 
nrepl/elisp/cider-ritz.el
1039:If FACE is nil, `nrepl-dbg-frame-line-face' is used."
1040:  (setq face (or face 'nrepl-dbg-frame-line-face))
custard-tart% ag nrepl-dbg-hook
nrepl/elisp/cider-ritz.el
919:        (run-hooks 'nrepl-dbg-hook)
custard-tart% ag nrepl-dbg-recenter-region
nrepl/elisp/cider-ritz.el
1287:  (nrepl-dbg-recenter-region start end))
custard-tart% ag nrepl-dbg-section-face
nrepl/elisp/cider-ritz.el
1032:             face nrepl-dbg-section-face
custard-tart% ag nrepl-dbg-up
nrepl/elisp/cider-ritz.el
1436:  (nrepl-dbg-move-with-details 'nrepl-dbg-up))
```

**Comment by jjl** [comment]
I think I've got them all now. Through exhaustively checking that symbols were bound and then manually going through the rest to see if anything else resolved.

**Comment by avocade** [comment]
+1 :) 

Progress stopped on ritz btw? What's the replacement if so?

**Comment by jjl** [comment]
NFC. But since the author hasn't bothered to even acknowledge my bug report in 4 months, it isn't going to be this.

**Comment by hugoduncan** [comment]
@jjl Things get overlooked sometimes, my apologies. Swearing isn't going to motivate to do anything though.

I've not found time to work on ritz in a while.  If anyone wants to help out with getting things working with cider, I'm open to giving commit rights to the project.  With cider moving to using middleware for everything, it should be easier to integrate with now.

**Comment by avocade** [comment]
Hey Duncan, really great stuff you've done. I'm more curious of what you're using yourself now. An alternative to ritz or are you simply staying on the older nrepl?

**Comment by hugoduncan** [comment]
@avocade I'm just using plain cider at the moment.

**Comment by jjl** [comment]
Hey,

Sorry, had a stressful day yesterday and you're absolutely right, I shouldn't have sworn at you.

I'm liable to fork at some point so I can fix these things. Now I know you don't have time and I've been reminded of ritz's existence, I'm somewhat more liable to just take the time and fix things.

**Pull request closed without merging**
